language: node_js
node_js:
  - "node"
# FOR SPEED
# cache:
#   directories:
#     - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: develop
  local_dir: dist
  target_branch: master
script: npm start
